fdi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('banking/', include('fdi_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fdi_app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('fdi/', HomePage, name="home"),
    path('fdi/about/', AboutUs, name="about"),
    path('fdi/service/', Service, name="service"),
    path('fdi/supervisors/', Guard, name="supervisors"),
    path('fdi/contact/', ContactUS, name="contact"),
    path('fdi/register/', register, name="register"),
    path('fdi/login/', LoginView.as_view(template_name='main/login.html'), name="login"),
    path('fdi/logout/confirm/', Logout_Confirm, name='logout-confirm'),
    path('fdi/logout/', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('fdi/personal/profile/', transfer_money, name="profile"),
    path('fdi/personal/profile/history', history, name="history"),
    # path('fdi/personal/profile/transfer/', , name="transfer_money")
]

fdi_app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self) -> str:
        return f'{self.user.username} profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)


        if img.height > 300  or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path, quality=95)

class Tranfer(models.Model):
    bank_name = models.CharField(max_length=100, blank=False, null=False)
    account_number = models.IntegerField(blank=False, null=False)
    amount = models.IntegerField(blank=False, null=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.bank_name}, {self.account_number}, {self.amount}"

fdi_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Tranfer

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label="First Name")
    last_name = forms.CharField(max_length=30, required=True, label="Last Name")
    email = forms.EmailField(required=True, label="Email Address")

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class TranferForm(forms.ModelForm):
    class Meta:
        model = Tranfer
        fields = ['bank_name', 'account_number', 'amount']

fdi_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, TranferForm
from .models import Tranfer
from django.contrib.auth.decorators import login_required

# Create your views here.
def HomePage(request):
    return render(request, 'main/index.html')

def AboutUs(request):
    return render(request, 'main/about.html')

def ContactUS(request):
    return render(request, 'main/contact.html')

def Service(request):
    return render(request, 'main/service.html')

def Guard(request):
    return render(request, 'main/guard.html')


@login_required
def Logout_Confirm(request):
    return render(request, 'main/logout.html')

@login_required
def history(request):
    transfers = Tranfer.objects.all().order_by('-date_created')
    return render(request, 'main/history.html', {'transfers':transfers})

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been created! You can now log in.")
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'main/register.html', {'form': form})

# @login_required
# def profile(request):
#     if  request.method == 'POST':
#         p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
#         if p_form.is_valid():
#             p_form.save()
#             messages.success(request, f'Your account is updated')
#             return redirect('profile')
#     else:
#         p_form = ProfileUpdateForm(instance=request.user.profile)
#     context = {
#         'p_form' : p_form
#     }
#     return render(request, 'main/profile.html', context)


@login_required
def transfer_money(request):
    if request.method == "POST":
        form = TranferForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Money Transferred successfully')
            return redirect('profile')
    else:
        form = TranferForm()
    context = {'form': form}
    return render(request, 'main/profile.html', context)

# @login_required
# def recent_transfer(request):
#     transfers = Tranfer.objects.all()
#     return render(request, 'main/history.html', {'transfers':transfers})
    

fdi_app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">

  <title>FID Banking</title>

  <!-- bootstrap core css -->

  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.css'%}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{%static 'css/style.css'%}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{%static 'css/responsive.css'%}" rel="stylesheet" />
</head>
{%url 'profile' as profile%}
{%url 'home' as home%}
{%url 'history' as history%}
<style>
  @keyframes spin {
      from {
          transform: rotate(0deg);
      }
      to {
          transform: rotate(360deg);
      }
  }
</style>
<body>
  <div class="hero_area">
    <!-- header section strats -->
    <div class="hero_bg_box">
      <div class="img-box">
        <img src="{%static 'images/Header.jpeg'%}" quality={100} alt="">
      </div>
    </div>

    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="contact_link-container">
            <a href="" class="contact_link1">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                us, france
              </span>
            </a>
            <a href="" class="contact_link2">
              
              <span>
                
              </span>
            </a>
            <a href="" class="contact_link3">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                fdibank@fincs.co.org 
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container">
            <a class="navbar-brand" href="{%url 'home' %}">
              <span>
                FDI Banking
              </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""></span>
            </button>

            <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
              <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item {%if request.path == home%} active {%else%}{%endif%}">
                  <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url "about"%}"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url "service"%}"> Services </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'contact'%}">Contact us</a>
                </li>
                <li class="nav-item {%if request.path == profile%} active {%else%}{%endif%}">
                  <a class="nav-link" href="{%url 'profile'%}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'history' %}">History</a>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'logout-confirm'%}">Logout</a>
                </li>
                {%else%}
                <li class="nav-item active">
                  <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url "about"%}"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url "service"%}"> Services </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'contact'%}">Contact us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'login'%}">Login</a>
                </li>
                <!-- <li class="nav-item">
                  <a class="nav-link" href="{%url 'register'%}">Register</a>
                </li> -->
                {% endif %}
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!-- end header section -->

    <div class="col-md-8">
      {%if messages%}
        {%for message in messages%}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {%endfor%}
      {%endif%}
    </div>




  {%block content%}
  {%endblock content%}








  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_logo">
            <a class="navbar-brand" href="index.html">
              <span>
                FDI Banking
              </span>
            </a>
            <p>
              When you choose our bank, you're choosing a partner you can trust. Join us on the journey towards a brighter financial future.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              We Provide
            </h5>
            <ul>
              <li>
                <a href="">
                  We prioritize security
                </a>
              </li>
              <li>
                <a href="">
                  Customer-centric approach
                </a>
              </li>
              <li>
                <a href="">
                  Financial stability
                </a>
              </li>
              <li>
                <a href="">
                  Innovation and technology
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Contact us
            </h5>
          </div>
          <div class="info_contact">
            <a href="" class="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                us, france
              </span>
            </a>
            <a href="" class="">
              <span>
              
              </span>
            </a>
            <a href="" class="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                fdibank@fincs.co.org
              </span>
            </a>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="#">
              <input type="email" placeholder="Enter your email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->




  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; <span id="currentYear"></span> All Rights Reserved.
    </p>
  </footer>
  <!-- footer section -->

  <!-- Load jQuery (Use only one version) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Load jQuery UI -->
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>

<!-- Load Font Awesome -->
<script src="https://kit.fontawesome.com/2ae773800d.js" crossorigin="anonymous"></script>

<!-- Load Bootstrap -->
<script src="{% static 'js/bootstrap.js' %}"></script>

<!-- Load Custom JS -->
<script src="{% static 'js/custom.js' %}"></script>

<!-- Initialize jQuery UI Dialog -->
<script>
  $(document).ready(function () {
    // Initialize both dialogs
    $("#transfer-dialog").dialog({
        autoOpen: false,
        modal: true,
        width: 400,
        show: { effect: "fade", duration: 300 },
        hide: { effect: "fade", duration: 300 },
    });

    $("#confirm-dialog").dialog({
        autoOpen: false,
        modal: true,
        width: 400,
        show: { effect: "fade", duration: 300 },
        hide: { effect: "fade", duration: 300 },
    });

    // Open the transfer dialog
    $("#open-dialog").click(function () {
        $("#transfer-dialog").dialog("open");
    });

    // Show confirmation dialog on "Next"
    $("#submitTransfer").click(function () {
        $("#transfer-dialog").dialog("close");
        $("#confirm-dialog").dialog("open");
    });


    // Confirm button: Show the spinner, wait 3.5 seconds, and then submit the form
    $("#confirm-transfer").click(function () {
        $("#loading-spinner").show(); // Show the spinner
        $("#confirmation-message").hide()
        $("#confirm-transfer, #cancel-transfer").hide(); // Hide the buttons
        setTimeout(function () {
            $("#transfer-form").submit(); // Submit the form after 3.5 seconds
        }, 4500);
    });

    // Cancel button: close the confirmation dialog
    $("#cancel-transfer").click(function () {
        $("#confirm-dialog").dialog("close");
    });
});


</script>

</body>

</html>

fdi_app/templates/main/about.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6 px-0">
          <div class="img_container">
            <div class="img-box">
              <img src="{%static 'images/about-us.jpeg'%}" alt="" />
            </div>
          </div>
        </div>
        <div class="col-md-6 px-0">
          <div class="detail-box">
            <div class="heading_container ">
              <h2>
                Who Are We?
              </h2>
            </div>
            <p>
              Welcome to Federal Direct Investment Bank (FDI), where we are committed to being your trusted financial partner.
               At FDI Bank, we understand that each customer has unique financial goals and aspirations, 
               and we are here to help you achieve them.
               Our bank was founded on the principles of integrity, transparency,
               and customer satisfaction. We believe in building lasting relationships with our
                customers based on trust and mutual respect. 
            </p>
            <div class="btn-box">
              <a href="">
                Read More
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  {%endblock content%}

fdi_app/templates/main/contact.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

  <!-- contact section -->

  <section class="contact_section layout_padding">
    <div class="contact_bg_box">
      <div class="img-box">
        <img src="{%static 'images/contact-bg.jpg'%}" alt="">
      </div>
    </div>
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Get In touch
        </h2>
      </div>
      <div class="">
        <div class="row">
          <div class="col-md-7 mx-auto">
            <form action="#">
              <div class="contact_form-container">
                <div>
                  <div>
                    <input type="text" placeholder="Full Name" />
                  </div>
                  <div>
                    <input type="email" placeholder="Email " />
                  </div>
                  <div>
                    <input type="text" placeholder="Phone Number" />
                  </div>
                  <div class="">
                    <input type="text" placeholder="Message" class="message_input" />
                  </div>
                  <div class="btn-box ">
                    <button type="submit">
                      Send
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end contact section -->

  {%endblock content%}

fdi_app/templates/main/history.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

{% if request.user.is_superuser %}
<div class="bg-secondary text-white p-1">
    <!-- Table Title -->
    <div class="table-title">
        <h3 style="background-color: rgb(23, 22, 22); text-align: center; border-radius: 8px; padding: 10px;">Historys</h3>
    </div>

    <!-- Table -->
     {%for tranfer in transfers%}
     <table class="table-fill" style="margin-top: 30px;">
         <thead>
            <tr>
                <th class="text-left">Account <br/> Name</th>
                <th class="text-left"></th>
                <th class="text-left">Account <br/> Number</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            <!-- User Account Information -->
            <tr>
                {% if request.user.username == "Helenacastle" %}
                    <td class="text-left">Helena</td> 
                    <td class="text-left">Castle</td>
                {% else %}
                <td class="text-left">{{ request.user.first_name }}</td> 
                    <td class="text-left">{{ request.user.last_name }}</td>
                {% endif %}
                <td class="text-left">{{tranfer.account_number}}</td>
            </tr>

            <!-- Transaction Details -->
            <tr>
                <td class="text-left bold">Money Transferred</td>
                <td class="bold">Bank Name</td>
                <td></td>
            </tr>
            <tr>
                <td class="text-left text-success"> &#36;{{tranfer.amount}}</td>
                <td>{{tranfer.bank_name}}</td>
                <td></td>
            </tr>

            <!-- Additional Information -->
            <tr>
                <td class="text-left bold">Date</td>
                <td class="text-left bold">Description</td>  
                <td></td>              
            </tr>
            <tr>
                <td class="text-left">{{tranfer.date_created}}</td>
                <td class="text-left" style="color: #2196F3;">Pending</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    {%endfor%}
</div>
{% endif %}

{% endblock content %}

fdi_app/templates/main/login.html
{%load static%}
{%block content%}
<head>
    <link href="{%static 'css/register.css'%}" rel="stylesheet" />
</head>



<div class="login">
	<h1>Login</h1>
    <form method="post">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block btn-large">Login Account.</button>
    </form>
</div>
{%endblock content%}

fdi_app/templates/main/logout.html
{%block content%}
{%load static%}
<head>
    <link href="{%static 'css/register.css'%}" rel="stylesheet" />
</head>
<div class="login">
<form  action="{%url 'logout'%}" method="post">
    <h2 class="tm-color-primary tm-post-title mb-4">Are you sure you want to logout</h2>
    {% csrf_token %}
    <button type="submit" style="padding : 10px; padding-left: 20px; padding-right: 20px; color: red;">logout</button> 
    <a href='{% url "home" %}' class='go_back'>Go back</a>
</form>
</div>
{%endblock content%}

fdi_app/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

{%if request.user.is_superuser%}
<div class="">
    <div class='bg-secondary text-white p-1'>
         <div class="content-section" style="margin-bottom: 70px; margin-top: 50px;">
            <div style="display: flex; gap: 20px; flex-wrap: wrap; justify-content: center;">
            <div>
                <img src="{{ user.profile.image.url }}" height="200" width="200" quality="100" loading="lazy" alt="">
            </div>
            <div>
                <div class="media-body">
                    <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
                    <p class="account-heading">{{ user.email }}</p>
                    <h2 class="mt-3">Account Balance</h2>
                    <h2 class="money" style="font-size: 20px; padding: 10px; border-radius: 8px; background-color:white; color:green; width:250px">USD $13,159,824.40</h2>
                    <button id="open-dialog" class="tansfer-button" style="border: none; border-radius: 8px; background-color: black; color: white; padding:7px; margin-top: 8px;">Transfer Money</button>
                </div>
            </div> 
            </div>
            
            </div> 

<div id="transfer-dialog" title="Transfer Money" style="display: none;">
    <form id="transfer-form" method="POST" action="{% url 'profile' %}" style="background-color: black; color: white; padding: 1rem; border-radius: 0.375rem;">
        {% csrf_token %}
        
        <label for="id_bank_name" style="display: block; font-weight: bold; color: white; margin-bottom: 0.5rem;">Bank Name (full name)</label>
        {{ form.bank_name }}
        <br><br>
    
        <label for="id_account_number" style="display: block; font-weight: bold; color: white; margin-bottom: 0.5rem;">Account Number</label>
        {{ form.account_number }}
        <br><br>
    
        <label for="id_amount" style="display: block; font-weight: bold; color: white; margin-bottom: 0.5rem;">Amount to Transfer</label>
        {{ form.amount }}
        <br><br>
    
        <button 
            type="button" 
            id="submitTransfer" 
            style="margin-top: 20px; border: none; padding: 10px 15px; color: white; background-color: green; border-radius: 8px; font-weight: bold;">
            Transfer Money
        </button>
    </form>
    
</div>

<!-- Confirmation Dialog -->
<div id="confirm-dialog" title="Confirm Transfer" style="display: none;">
    <p id="confirmation-message">Are you sure you want to transfer the money?</p>
    <div id="loading-spinner" style="display: none; text-align: center; margin-top: 10px;">
        <div class="spinner" style="border: 8px solid rgba(0, 0, 0, 0.1); border-left-color: #007bff; border-radius: 50%; width: 100px; height: 100px; animation: spin 1s linear infinite;"></div>
        <p style="margin-top: 10px;">Processing...</p>
    </div>
    <button id="confirm-transfer" style="padding: 5px 10px; background-color: green; color: white; border: none; border-radius: 8px;">Confirm</button>
    <button id="cancel-transfer" style="padding: 5px 10px; background-color: red; color: white; border: none; border-radius: 8px;">Cancel</button>
</div>


          <!-- On tables -->
          <div class="table-title">
            {% comment %} <h3>History</h3> {% endcomment %}
            </div>
            <table class="table-fill">
            <thead>
            
                <tr class="table-flex" style="background-color: black;"> 
                    <th class="text-left" style="color: #dedede; padding: 20px;  font-size: 20px;  font-weight: 0px;">Personal accounts</th>
                    <th class="text-left"><img class="rounded-circle account-img" style="height:90px; width:100px" src="{{ user.profile.image.url }}"></th>
                <tr>

            <th class="text-left">Account  Name</th>
            <th class="text-left"></th>
            <th class="text-left">Account <br/> Number</th>

            </tr>
        </thead>
            <tbody class="table-hover">
                <tr>
                {% if request.user.username == "Helenacastle" %}
                <td class="text-left">Helena</td> 
                <td class="text-left">Castle</td>
                {% else %}
                <td class="text-left">{{request.user.first_name }}</td> 
                <td class="text-left">{{ request.user.last_name }}</td>
                {% endif %}
                {% comment %} <td class="text-left">USD $50,000.00</td> {% endcomment %}
                <td class="text-left">0500016M024</td>
            </tr>

            <tr>
                <td class="text-left bold">Amount Invested</td>
                <td class="text-left bold"></td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                <td class="text-left  bold">Year</td>
            </tr>

            <tr>
                <td class="text-left text-success">USD $2,709,001</td>
                <td class="text-left"></td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                <td class="text-left ">2017</td>
            </tr>

            <tr>
                <td class="text-left bold">Accumulated Interest</td>
                <td class="text-left bold"></td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                <td class="text-left text-success bold"></td>
            </tr>
            
            <tr>
                <td class="text-left text-success">USD $10,450,825.79</td>
                <td class="text-left"></td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                <td class="text-left text-success"></td>
            </tr>
           
            <tr>
            <!-- <td class="text-left bold">Routing #</td> -->
            <td class="text-left bold"></td>
            {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
            <td class="text-left text-success bold">Avail. Balance</td>
        </tr>

            <tr>
                <td class="text-left">272484894</td>
                <td class="text-left">USD $13,159,824.40</td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                <td class="text-left text-success">USD $13,159,824.40</td>
            </tr>

            <tr>
                <td class="text-left bold">Date</td>
                <td class="text-left bold">Description</td>
                {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                {% comment %} <td class="text-left text-success">USD $3,587,345.00</td> {% endcomment %}
                </tr>
                
                <tr>
                    <td class="text-left" >
                        <p id='currentDate'></p>
                        <p id='currentTime'></p>
                    </td>
                    <td class="text-left text-success">Active</td>
                    {% comment %} <td class="text-left">USD $5,000.00</td> {% endcomment %}
                    {% comment %} <td class="text-left text-success">USD $3,587,345.00</td> {% endcomment %}
                </tr>
            
                
            </tbody>
            </table>
              
            

        </div>
</div>
{%else%}
{%endif%}
{% endblock content %}

fdi_app/templates/main/register.html
{% comment %} {%extends 'base.html'%} {% endcomment %}
{%load static%}
{%block content%}
<head>
    <link href="{%static 'css/register.css'%}" rel="stylesheet" />
</head>
<div class="login">
	<h1>Resgister Here</h1>
    <form method="post">
        {% csrf_token %}
    	{{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block btn-large">Create Account.</button>
    </form>
</div>
{%endblock content%}